### ISSUE TITLE
Update protos and codegen with latest protos

### ISSUE THREAD

**Issue by puneet2019** [cosmology-tech/stargaze-zone#6]
Opening this issue to update protos for https://github.com/public-awesome/stargaze
It would be better to have both v13.x and v12.x protos because the proto paths have changed. 
Testnet is on 13.x while mainnet is on 12.x ! 

temperorily to unblock myself I have added the protos to [persistenceJS](https://github.com/persistenceOne/persistenceJS/tree/puneet/persistence%2Bstargaze), because we have all telescope and npm setup there . 
But would be great to have it here, since it is the only library for stargazejs.

**Comment by Zetazzz** [comment]
Published updated version:
 - stargaze-query@0.15.4
 - stargazejs@0.14.3

If there're other problems please let me know!
Thank you very much!
